from constants import COMPANIES_TICKERS_TESLA_DISNEY_META # More sets may be added here for convenience.

COMPANIES_SET = COMPANIES_TICKERS_TESLA_DISNEY_META

# Todo: why separate sets?
START_DATE = '2021-03-01'
END_DATE = '2022-03-01'
SHARE_PRICES_FETCHING_START_DATE = '2021-03-01'
SHARE_PRICES_FETCHING_END_DATE = '2022-03-01'

SUB_PERIOD_LENGTH_IN_DAYS_ARRAY = [10]
ATTRIBUTE_OF_DECISION_INDEX = 3
