POLYGON_AVAILABLE_COMPANIES_SET = [
    # 'TSLA', 'MSFT', 'NFLX', 'AMZN', 'GOOGL',
    'PYPL', 'DIS', 'AAPL', 'SQ', 'NVDA',
    # 'KO'
]
COMPANIES_SET = POLYGON_AVAILABLE_COMPANIES_SET
# NOT AVAILABLE ON POLYGON: SPOT

START_DATE = '2022-01-01'
END_DATE = '2024-01-01'

SUB_PERIOD_LENGTH_IN_DAYS_ARRAY = [20]
NUMBER_OF_REPORTS_TAKEN_FOR_CALCULATION = 4

# Todo: automate it
NUMBER_OF_REPORTS_TO_FETCH_FROM_API = 14
